# Generated by Django 4.2 on 2024-02-10 19:50

from django.db import migrations, models
import utils.generate_code


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="profile",
            new_name="user",
        ),
        migrations.AddField(
            model_name="profile",
            name="code",
            field=models.CharField(
                default=utils.generate_code.generate_code, max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="profile"),
        ),
    ]
