# Generated by Django 4.2 on 2024-01-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeleveryFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fee", models.FloatField(default=5)),
            ],
        ),
    ]
