# Generated by Django 4.2 on 2023-10-16 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("product", "0004_brand_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("InProgress", "InProgress"),
                            ("Completed", "Completed"),
                        ],
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cart_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, verbose_name="Code")),
                ("discount", models.IntegerField(verbose_name="Discount")),
                ("quantity", models.IntegerField(verbose_name="Quantity")),
                (
                    "start_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Start Date"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="End Date"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.FloatField(verbose_name="Price")),
                ("quntity", models.IntegerField(verbose_name="Quantity")),
                ("total", models.FloatField(verbose_name="Total")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_detail",
                        to="order.cart",
                        verbose_name="Order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="oredr_product",
                        to="product.product",
                        verbose_name="Product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Recieved", "Recieved"),
                            ("Processed", "Processed"),
                            ("Shipped", "Shipped"),
                            ("Delivered", "Delivered"),
                        ],
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default="OQCK1U1W", max_length=50, verbose_name="Code"
                    ),
                ),
                (
                    "order_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Oder Time"
                    ),
                ),
                (
                    "delivery_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Delivery Time"
                    ),
                ),
                (
                    "total_after_coupon",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Total-Coupon"
                    ),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coupon_order",
                        to="order.coupon",
                        verbose_name="Coupon",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CartDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quntity", models.IntegerField(verbose_name="Quantity")),
                ("total", models.FloatField(verbose_name="Total")),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_detail",
                        to="order.cart",
                        verbose_name="Cart",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_product",
                        to="product.product",
                        verbose_name="Product",
                    ),
                ),
            ],
        ),
    ]
