# Generated by Django 4.2 on 2023-11-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartdetail",
            old_name="quntity",
            new_name="quantity",
        ),
        migrations.AlterField(
            model_name="order",
            name="code",
            field=models.CharField(
                default="U0WMGAUU", max_length=50, verbose_name="Code"
            ),
        ),
    ]
