# Generated by Django 4.2 on 2023-12-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_rename_quntity_cartdetail_quantity_alter_order_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="code",
            field=models.CharField(
                default="2BMNKCV9", max_length=50, verbose_name="Code"
            ),
        ),
    ]
