# Generated by Django 4.2 on 2023-12-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0004_alter_order_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="code",
            field=models.CharField(max_length=50, verbose_name="Code"),
        ),
    ]
