# Generated by Django 4.2 on 2023-12-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0007_rename_quntity_orderdetail_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="code",
            field=models.CharField(
                blank=True,
                default="PM2Y2B9J",
                max_length=50,
                null=True,
                verbose_name="Code",
            ),
        ),
    ]
