# Generated by Django 4.2 on 2023-12-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0008_alter_order_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartdetail",
            name="quantity",
            field=models.IntegerField(default=0, verbose_name="Quantity"),
        ),
        migrations.AlterField(
            model_name="order",
            name="code",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Code"
            ),
        ),
    ]
