# Generated by Django 4.2 on 2023-12-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0009_alter_cartdetail_quantity_alter_order_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartdetail",
            name="quantity",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Quantity"
            ),
        ),
    ]
