# Generated by Django 4.2 on 2023-12-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0010_alter_cartdetail_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartdetail",
            name="total",
            field=models.FloatField(default=0, verbose_name="Total"),
        ),
    ]
