# Generated by Django 4.2 on 2024-01-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0012_cart_coupon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Recieved", "Recieved"),
                    ("Processed", "Processed"),
                    ("Shipped", "Shipped"),
                    ("Delivered", "Delivered"),
                ],
                default="Recieved",
                max_length=10,
                verbose_name="Status",
            ),
        ),
    ]
