# Generated by Django 4.2 on 2024-01-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0013_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="total_after_coupon",
            field=models.FloatField(blank=True, null=True, verbose_name="Total-Coupon"),
        ),
    ]
